bug fix: JSON parameters
certtools/intelmq-manager pull request #174
Opened 2019-01-02 19:11 UTC by e3rd

Before when I saved a JSON-like string as a bot parameter in Manager and reloaded the page, I got displayed [object Object] because it was internally converted to a JSON:

![image](https://user-images.githubusercontent.com/6942231/50607719-732ca880-0eca-11e9-9323-a020d1348b2f.png)

Now that's fixed both on Configuration and Monitor page:

![image](https://user-images.githubusercontent.com/6942231/50607689-5f814200-0eca-11e9-8a5d-95052ddde894.png)

![image](https://user-images.githubusercontent.com/6942231/50607679-57290700-0eca-11e9-8519-2d9078a48a28.png)

2019-03-19 15:34 UTC, e3rd commented
ping :)

2019-03-21 14:09 UTC, ghost requested changes
Thanks, that is very useful!

The 'Edit Node' window doesn't have a scrollbar anymore :/

When pressing enter 'cause I can't press the submit button it adds an additional parameter http_proxy to the configuration.

2019-03-21 14:38 UTC, wagner-certat commented
That fixes one part of https://github.com/certtools/intelmq-manager/issues/81 btw

2019-03-25 15:57 UTC, e3rd commented
Sorry, my bad. I couldn't handle `null` before because in JavaScript, you know, *null is an [buggy object](http://2ality.com/2013/10/typeof-null.html)* :D . Now we handle null, list and dict objects properly.

2019-03-25 16:36 UTC, ghost approved these changes
works like a charm :)

2019-03-25 16:52 UTC, merged